version: "3"

services:
  app:
    build: ./
    ports:
      - 8501:8501
    command: "streamlit run ./src/app.py"

  nginx:
    image: "nginx:stable"
    depends_on:
      - app
    links:
      - app
    restart: always
    ports:
      - 80:80
    volumes:
      - "./deployment/nginx.conf:/etc/nginx/nginx.conf"